#!/bin/sh

DAEMON="ledbetter-client"
BINFILE="/usr/bin/$DAEMON"
CONFIG="/usr/share/ledbetter/config.toml"
PIDFILE="/var/run/$DAEMON.pid"
LOGFILE="/var/log/$DAEMON.log"

start() {
        printf 'Starting %s: ' "$DAEMON"
        # Wait for entropy to be available before starting ledbetter
        start-stop-daemon -b -m -S -q -p "$PIDFILE" -x /bin/sh \
                -- -c "head -c 128 /dev/random >/dev/null && exec $BINFILE --config $CONFIG >$LOGFILE 2>&1"
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

stop() {
        printf 'Stopping %s: ' "$DAEMON"
        start-stop-daemon -K -q -p "$PIDFILE"
        status=$?
        if [ "$status" -eq 0 ]; then
                rm -f "$PIDFILE"
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

restart() {
        stop
        sleep 1
        start
}

case "$1" in
        start|stop|restart)
                "$1";;
        reload)
                # Restart, since there is no true "reload" feature.
                restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
