#!/bin/sh
#
# Load required kernel modules...
#

case "$1" in
  start)
	printf "Loading kernel modules: "
	modprobe brcmfmac
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Unloading kernel modules: "
	modprobe -r brcmfmac
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
